name: enzyme-screening-platform-opentrons
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - git
  - python=3.8
  - opentrons
  - pandas
  - docopt
  - r-base
  - r-ggplot2
  - r-dplyr
  - r-rjson
  - r-gridExtra
  - r-png
