name: "build"
on: [push]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: "Setup python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: 'Setup Opentrons framework' 
        run: pip install -r containers/requirements.txt
      - name: 'Testing protocol'
        run: opentrons_simulate protocol.py -e -o nothing
      - name: Push image to GitHub container registry
        if: startsWith(github.event.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: containers/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:0.0.0, ghcr.io/${{ github.repository }}:latest
